name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# cancel previous runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set GO version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Download dependencies
        run: go mod download

      - name: Run go vet
        run: go vet ./...

  test:
    runs-on: ubuntu-latest
    needs: [ lint, vet ]  # Only run if lint and vet succeed
    steps:
      - uses: actions/checkout@v4

      - name: Set GO version via common env file
        run: cat .github/env >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{env.GO_VERSION}}

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...
